---
abstract: 'Enhancement to PDL by using named dimensions. '
author:
  - 'Ingo Schmid <ingosch@gmx.at>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-Dims
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  PDL: 0
  Scalar::Util: 0
  perl: 5.012
version: 0.005002
